### ISSUE TITLE
License file should be renamed

### ISSUE THREAD

**Issue by graeme-a-stewart** [HEP-SF/tools#17]
Should be called `LICENSE.txt` for github to understand it automatically

See https://help.github.com/articles/licensing-a-repository/

**Comment by graeme-a-stewart** [comment]
Hmmm, even after that change license isn't picked up - odd and will require more investigation (format issue?)

**Comment by ktf** [comment]
You need `LICENSE` or `LICENSE.md` https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by graeme-a-stewart** [comment]
I found the issue - if you also have a `COPYRIGHT` file with non-license text in it then the `licensee` tool gets confused by this and won't declare an overall license classification.

`LICENSE`, `LICENSE.md` and `LICENSE.txt` all work.

OK, this is a spurious issue.
