### ISSUE TITLE
Update scripts to Python3

### ISSUE THREAD

**Issue by graeme-a-stewart** [HEP-SF/tools#20]
Now that Python2 is out of support we should update the scripts to Python3.

I had a look at the out-of-the-box Python3 versions in various distributions and the state of play is:

| Distro | Python3 |
|-----|-----|
| Ubuntu16 | 3.5 |
| CentOS7 | 3.6 |
| Ubuntu18 | 3.6 |
| CentOS8 | 3.6 |
| Ubuntu20 | 3.8 |

I believe we should make Python 3.6 the minimum version (which adds the wonderful f-strings 👍 )

**Comment by graeme-a-stewart** [comment]
Closed with PR #21

**Comment by hegner** [comment]
Thanks!
