### ISSUE TITLE
Vendor gtest in template or use catch?

### ISSUE THREAD

**Issue by drbenmorgan** [HEP-SF/tools#5]
The template project uses `find_package(gtest)` for locating tests, but the recommendation by the guest developers is to [vendor it in the client project](https://github.com/google/googletest/blob/master/googletest/docs/FAQ.md#why-is-it-not-recommended-to-install-a-pre-compiled-copy-of-google-test-for-example-into-usrlocal). Should the template project thus include a vendored copy of gtest? This appears to be pretty straightforward - just copy the sources in, add a library target, link tests to it. 

The other option would be to use the [catch](https://github.com/philsquared/Catch) framework, which appears to provide very similar functionality, and can be used a a single header file.

**Comment by hegner** [comment]
Copying in would make it rather heavy. Catch seems a good one indeed. I wouldn't object moving to that one instead. Do you have hands-on experience with it?

**Comment by drbenmorgan** [comment]
I've used Catch in a [postgrad teaching course](http://www2.warwick.ac.uk/fac/sci/physics/research/epp/resources/teaching/software_development_2015/day_3)  with good experience and feedback, so I feel it's a good one for projects to start with, especially at this template level. 

I can't speak for whether it offers greater or lesser features than other frameworks, but I guess that's more a task for documentation.

**Comment by hegner** [comment]
thanks. skimming what I could find it looks nice for small projects. Could you make a pull request to show how it would look like in this concrete case?

**Comment by hegner** [comment]
I played a little bit with catch and I in the meantime migrated two projects to using it. Really nice and lightweight

**Comment by drbenmorgan** [comment]
Marking this as closed as Catch was integrated in PR #9
