### ISSUE TITLE
Template project assumes presence of `hsf_get_platform.py`

### ISSUE THREAD

**Issue by drbenmorgan** [HEP-SF/tools#6]
The [Project template cpack module](project_template/cmake/HSFTEMPLATECPack.cmake#L36) assumes the presence (in `PATH`) of the `hsf_get_plaform.py` program. 

This should either:
- be copied into the project for direct use
- be installed with a cmake package config file, the template project then using `find_package`
- also provide a cmake implementation which can be supplied in the CPack template file.

Any preference amongst these?

**Comment by hegner** [comment]
As I assume this file to change over time, I wouldn't like having copies around. So the second option seems better to me. We could as well have a switch if you want to do without.

**Comment by drbenmorgan** [comment]
O.k., I'll take a look at implementing a switch in the first instance, so intended behaviour would be:
- If `hsf_get_platform.py` present, use it
- Else, use CMake/CPack standard platform variables.
